name: rift

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'rift command to run (e.g. list, start MyVM, exec --folder MyFolder "hostname" --user USER --pass PASSWORD)'
        required: true
        type: string

jobs:
  run:
    runs-on: self-hosted
    env:
      ENV_PATH: C:/actions-runner/.env
      RUNNER_TRACKING_ID: ""
    steps:
      - name: Run rift
        run: C:\actions-runner\rift.exe ${{ github.event.inputs.command }}
